<table>
  <tr>
    <td align=left>
      <a href='/network/'><img src='/images/neu/monitor.png' align=absmiddle border=0> Network</a>
    </td>
    <td width=5></td>
    <td align=left>
      <a href='/wiki/'><img src='/images/neu/edit.png' align=absmiddle border=0> Wiki</a>
    </td>
  </tr>
  <tr>
    <td align=left>
      <a href='http://customer.vostron.net/support/staff.cgi'><img src='/images/neu/info.png' align=absmiddle border=0> Support</a>
    </td>
    <td width=5></td>
    <td align=left>
      <a href='/dns/'><img src='/images/neu/dns.png' align=absmiddle border=0> DNS Admin</a>
    </td>
  </tr>
</table>
