<?php

d_echo('Venturi count sensors');

$tables = [
    [
        'mib_table' => 'VENTURI-SERVER-SYSTEM-MIB::vServerGeneralScalars',
        'mib_value' => 'VENTURI-SERVER-SYSTEM-MIB::vServerMaxClients',
        'oid' => '.1.3.6.1.4.1.3382.12.1.2.1.1.6.',
        'name' => 'max_clients',
        'descr' => 'Max Clients',
        'group' => 'Client Capacity',
        'type' => 'GAUGE',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-SYSTEM-MIB::vServerGeneralScalars',
        'mib_value' => 'VENTURI-SERVER-SYSTEM-MIB::vServerMaxClientless',
        'oid' => '.1.3.6.1.4.1.3382.12.1.2.1.1.7.',
        'name' => 'max_clientless',
        'descr' => 'Max Clientless',
        'group' => 'Client Capacity',
        'type' => 'GAUGE',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberTotalCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.4.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'subscriber_total_count',
        'descr' => 'Total Subscriber Count',
        'group' => 'Subscriber Count',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberCurrCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.5.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'subscriber_curr_count',
        'descr' => 'Current Subscriber Count',
        'group' => 'Subscriber Count',
        'type' => 'GAUGE',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberAuthenticationFailures',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.6.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_auth_failures',
        'descr' => 'Authentication Failures',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberAbortedConnections',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.7.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_aborted_conns',
        'descr' => 'Aborted Connections',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberReassignmentFailures',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.8.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_reassign_failures',
        'descr' => 'Reassignment Failures',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberStandbyCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.9.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_standby_count',
        'descr' => 'Standby Count',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberInactiveCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.10.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_inactive_count',
        'descr' => 'Inactive Count',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberReassignmentCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.11.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_reassign_count',
        'descr' => 'Reassignment Count',
        'group' => 'Subscriber Failure',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberUsageEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberByteCount',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.2.1.1.12.',
        'index' => 'VENTURI-SERVER-STATS-MIB::vServerSubscriberType',
        'name' => 'sub_byte_count',
        'descr' => 'Subscriber Traffic',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportPacketsSent',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.3.',
        'name' => 'tran_packets_tx',
        'descr' => 'Transport Packets Tx',
        'group' => 'Packets',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportPacketsRecd',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.4.',
        'name' => 'tran_packets_rx',
        'descr' => 'Transport Packets Rx',
        'group' => 'Packets',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportPacketsRetransmitted',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.5.',
        'name' => 'tran_packets_rexmit',
        'descr' => 'Transport Packets Rexmit',
        'group' => 'Packets',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportBytesSent',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.6.',
        'name' => 'tran_bytes_tx',
        'descr' => 'Transport Packets Tx',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportBytesRecd',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.7.',
        'name' => 'tran_bytes_rx',
        'descr' => 'Transport Bytes Rx',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportBytesRetransmitted',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.8.',
        'name' => 'tran_bytes_rexmit',
        'descr' => 'Transport Bytes Rexmit',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportUndeliverableToClients',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.9.',
        'name' => 'tran_undel_to_clients',
        'descr' => 'Transport Undeliverable To Clients',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportUndeliverableToComp',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.10.',
        'name' => 'tran_undel_to_comp',
        'descr' => 'Transport Undeliverable To Compressor',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportTotalConnections',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.11.',
        'name' => 'tran_total_conns',
        'descr' => 'Transport Total Connections',
        'group' => 'Connections',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportFailedConnections',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.12.',
        'name' => 'tran_failed_conns',
        'descr' => 'Transport Failed Connections',
        'group' => 'Connections',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportCurrentConnections',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.13.',
        'name' => 'tran_curr_conns',
        'descr' => 'Transport Current Connections',
        'group' => 'Connections',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportBytesToComp',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.14.',
        'name' => 'tran_bytes_to_comp',
        'descr' => 'Transport Bytes To Comp',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerTransportEntry',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerTransportBytesFromComp',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.3.2.1.1.14.',
        'name' => 'tran_bytes_from_comp',
        'descr' => 'Transport Bytes From Comp',
        'group' => 'Traffic',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerStatsSubscriberScalars',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerClientLimitExceeded',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.1.1.',
        'name' => 'client_limit_exceeded',
        'descr' => 'Client Limit Exceeded',
        'group' => 'Limits',
        'type' => 'COUNTER',
    ],
    [
        'mib_table' => 'VENTURI-SERVER-STATS-MIB::vServerStatsSubscriberScalars',
        'mib_value' => 'VENTURI-SERVER-STATS-MIB::vServerClientlessLimitExceeded',
        'oid' => '.1.3.6.1.4.1.3382.12.1.3.4.1.2.',
        'name' => 'clientless_limit_exceeded',
        'descr' => 'Clientless Limit Exceeded',
        'group' => 'Limits',
        'type' => 'COUNTER',
    ],
];

foreach ($tables as $table_value) {
    if (is_array($pre_cache[$table_value['mib_table']])) {
        foreach ($pre_cache[$table_value['mib_table']] as $key => $value) {

            $sensor_descr = $table_value['descr'];
            if (is_array($pre_cache[$table_value['index']])) {
                $sensor_descr = $table_value['descr'] . ' (' . $pre_cache[$table_value['index']][$key][$table_value['index']] . ')';
            }

            discover_sensor(
                null,
                'count',
                $device,
                $table_value['oid'] . $key,
                $key,
                $table_value['name'],
                $sensor_descr,
                1,
                1,
                null,
                null,
                null,
                null,
                $value['mib_value'],
                'snmp',
                null,
                null,
                null,
                $table_value['group'],
                $table_value['type'],
            );
        }
    }
}
