ALTER TABLE `users` ADD `created_at` TIMESTAMP NOT NULL DEFAULT '1970-01-02 00:00:01' AFTER `dashboard`;
ALTER TABLE `users`  ADD `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_at`;
ALTER TABLE `users`  ADD `remeber_token` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL AFTER `updated_at`;
