ALTER TABLE wireless_sensors CHANGE sensor_multiplier multiplier FLOAT NOT NULL DEFAULT 1;
UPDATE wireless_sensors SET multiplier = multiplier / sensor_divisor;
ALTER TABLE wireless_sensors ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE wireless_sensors CHANGE lastupdate updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wireless_sensors DROP sensor_deleted;
ALTER TABLE wireless_sensors ADD deleted_at TIMESTAMP NULL;
ALTER TABLE wireless_sensors CHANGE sensor_alert alert TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE wireless_sensors CHANGE sensor_custom custom_thresholds ENUM('No', 'Yes') NOT NULL DEFAULT 'No';
ALTER TABLE wireless_sensors CHANGE sensor_limit_low_warn warn_low FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_limit_low alert_low FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_limit_warn warn_high FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_limit alert_high FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_prev previous_value FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_current value FLOAT;
ALTER TABLE wireless_sensors CHANGE sensor_aggregator aggregator VARCHAR(16) NOT NULL DEFAULT 'sum';
ALTER TABLE wireless_sensors CHANGE sensor_oids oids TEXT NOT NULL;
ALTER TABLE wireless_sensors CHANGE sensor_index `index` VARCHAR(64);
ALTER TABLE wireless_sensors CHANGE sensor_type subtype VARCHAR(255) NOT NULL;
ALTER TABLE wireless_sensors CHANGE sensor_descr description VARCHAR(255);
ALTER TABLE wireless_sensors CHANGE sensor_class type VARCHAR(64) NOT NULL;
ALTER TABLE wireless_sensors CHANGE sensor_id wireless_sensor_id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE wireless_sensors MODIFY COLUMN access_point_id INT(11) AFTER device_id, MODIFY COLUMN oids TEXT NOT NULL AFTER description, MODIFY COLUMN type VARCHAR(64) NOT NULL AFTER access_point_id, MODIFY COLUMN `index` VARCHAR(64) AFTER description, MODIFY COLUMN subtype VARCHAR(255) NOT NULL AFTER description, MODIFY COLUMN warn_high FLOAT AFTER alert_low, MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE wireless_sensors DROP COLUMN sensor_divisor;
ALTER TABLE wireless_sensors DROP COLUMN entPhysicalIndex;
ALTER TABLE wireless_sensors DROP COLUMN entPhysicalIndex_measured;
