CREATE TABLE `ports_nac` (
  `ports_nac_id` int(11) NOT NULL AUTO_INCREMENT,
  `auth_id` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `device_id` int(11) NOT NULL,
  `port_id` int(11) NOT NULL,
  `port_index` bigint(20) NOT NULL,
  `port_descr` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionMacAddress` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionIPAddress` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionAuthzStatus` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionDomain` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionHostMode` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionUserName` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionAuthzBy` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionTimeOut` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionTimeLeft` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortAuthSessionAuthcStatus` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PortSessionMethod` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ports_nac_id`),
  KEY `device_id` (`device_id`),
  KEY `port_id` (`port_id`),
  KEY `ifIndex` (`port_index`),
  KEY `ifDescr` (`port_descr`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci	
