os: esphome
text: 'ESP-Home'
type: appliance
icon: esphome
snmp_bulk: false
over:
    - { graph: device_mempool, text: 'Heap Usage' }
    - { graph: device_dbm, text: 'RSSI' }
discovery:
    - sysDescr:
          - 'ESPHome'
poller_modules:
    sensors: true
    mempools: true
discovery_modules:
    sensors: true
    mempools: true
