<?php

/**
 * QueryBuilderParser.php
 *
 * -Description-
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @link       https://www.librenms.org
 *
 * @copyright  2018 Tony Murray
 * @author     Tony Murray <murraytony@gmail.com>
 */

namespace LibreNMS\Alerting;

use App\Facades\LibrenmsConfig;
use Illuminate\Support\Str;
use LibreNMS\DB\Schema;

class QueryBuilderParser implements \JsonSerializable
{
    protected static array $operators = [
        'equal' => '=',
        'not_equal' => '!=',
        'less' => '<',
        'less_or_equal' => '<=',
        'greater' => '>',
        'greater_or_equal' => '>=',
        'between' => 'BETWEEN',
        'not_between' => 'NOT BETWEEN',
        'begins_with' => 'LIKE',
        'not_begins_with' => 'NOT LIKE',
        'contains' => 'LIKE',
        'not_contains' => 'NOT LIKE',
        'ends_with' => 'LIKE',
        'not_ends_with' => 'NOT LIKE',
        'is_empty' => '=',
        'is_not_empty' => '!=',
        'is_null' => 'IS NULL',
        'is_not_null' => 'IS NOT NULL',
        'regex' => 'REGEXP',
        'not_regex' => 'NOT REGEXP',
        'in' => 'IN',
        'not_in' => 'NOT IN',
        'in_prefix' => 'IN_PREFIX',
        'not_in_prefix' => 'NOT_IN_PREFIX',
    ];

    protected static array $values = [
        'between' => '? AND ?',
        'not_between' => '? AND ?',
        'begins_with' => "'?%'",
        'not_begins_with' => "'?%'",
        'contains' => "'%?%'",
        'not_contains' => "'%?%'",
        'ends_with' => "'%?'",
        'not_ends_with' => "'%?'",
        'is_null' => '',
        'is_not_null' => '',
        'is_empty' => "''",
        'is_not_empty' => "''",
    ];
    protected Schema $schema;
    private array $tables;

    private function __construct(protected array $builder)
    {
        $this->schema = new Schema();
    }

    /**
     * Get all tables used by this rule
     */
    public function getTables(): array
    {
        if (! isset($this->tables)) {
            $this->tables = $this->findTablesRecursive($this->builder);
        }

        return $this->tables;
    }

    /**
     * Recursively find tables (including expanding macros) in the given rules
     *
     * @param  array{rules: array<array{field: string, operator: string, value: mixed}>}  $rules
     * @return string[] List of tables found in rules
     */
    protected function findTablesRecursive(array $rules): array
    {
        $tables = [];

        foreach ($rules['rules'] ?? [] as $rule) {
            if (array_key_exists('rules', $rule)) {
                $tables = array_merge($this->findTablesRecursive($rule), $tables);
            } elseif (Str::contains($rule['field'], '.')) {
                [$table, $column] = explode('.', (string) $rule['field']);

                if ($table == 'macros') {
                    $tables = array_merge($this->expandMacro($rule['field'], true), $tables);
                } else {
                    $tables[] = $table;
                }
            }
        }

        // resolve glue tables (remove duplicates)
        foreach (array_keys(array_flip($tables)) as $table) {
            $rp = $this->schema->findRelationshipPath($table);
            if ($rp) {
                $tables = array_merge($rp, $tables);
            }
        }

        // remove duplicates
        return array_keys(array_flip($tables));
    }

    /**
     * Initialize this from json generated by jQuery QueryBuilder
     */
    public static function fromJson(array|string|null $json): static
    {
        $json ??= [];

        if (! is_array($json)) {
            $json = json_decode($json, true) ?: [];
        }

        return new static($json);
    }

    /**
     * Get the SQL for this rule, ready to execute with device_id supplied as the parameter
     * If $expand is false, this will return a more readable representation of the rule, but not executable.
     *
     * @return null|string The rule or null if this is invalid.
     */
    public function toSql(bool $expand = true): ?string
    {
        if (empty($this->builder) || ! array_key_exists('condition', $this->builder)) {
            return null;
        }

        $sql = '';
        $wrap = false;

        if ($expand) {
            $sql = 'SELECT * FROM ' . implode(',', $this->getTables());
            $sql .= ' WHERE (' . implode(' AND ', $this->generateGlue()) . ') AND ';

            // only wrap in ( ) if the condition is OR and there is more than one rule
            $wrap = $this->builder['condition'] == 'OR' && count($this->builder['rules']) > 1;
        }

        return $sql . $this->parseGroup($this->builder, $expand, $wrap);
    }

    /**
     * Parse a rule group
     *
     * @param  array{condition: string, rules: array}  $rule
     * @param  bool  $expand  Expand macros?
     * @param  bool  $wrap  Wrap in parenthesis
     */
    private function parseGroup(array $rule, bool $expand = false, bool $wrap = true): string
    {
        $group_rules = [];

        foreach ($rule['rules'] as $group_rule) {
            if (array_key_exists('condition', $group_rule)) {
                $group_rules[] = $this->parseGroup($group_rule, $expand);
            } else {
                $group_rules[] = $this->parseRule($group_rule, $expand);
            }
        }

        $sql = implode(" {$rule['condition']} ", $group_rules);

        if ($wrap) {
            return "($sql)";
        } else {
            return "$sql";
        }
    }

    /**
     * Parse a rule
     *
     * @param  array{field: string, operator: string, value: mixed}  $rule
     * @param  bool  $expand  Expand macros?
     */
    protected function parseRule(array $rule, bool $expand = false): string
    {
        $field = $rule['field'];
        $builder_op = $rule['operator'];
        $op = self::$operators[$builder_op];
        $value = $rule['value'];

        if (is_string($value) && Str::startsWith($value, '`') && Str::endsWith($value, '`')) {
            // pass through value such as field
            $value = trim($value, '`');
            if ($expand) {
                $value = $this->expandMacro($value);
            }
        } elseif (isset(self::$values[$builder_op])) {
            // wrap values as needed (is null values don't contain ? so '' is returned)
            $values = (array) $value;
            $value = preg_replace_callback('/\?/', function ($matches) use (&$values) {
                return array_shift($values);
            }, self::$values[$builder_op]);
        } elseif (! is_numeric($value)) {
            // wrap quotes around non-numeric values
            $value = "\"$value\"";
        }

        if ($expand) {
            $field = $this->expandMacro($field);
        }

        if ($builder_op === 'in_prefix' || $builder_op === 'not_in_prefix') {
            return $this->buildPrefixSql($field, $rule['value'], $builder_op === 'not_in_prefix');
        }

        return trim("$field $op $value");
    }

    /**
     * Build a SQL expression for prefix membership testing (IPv4 and IPv6).
     *
     * @param  string  $field  SQL field expression (may include table prefix)
     * @param  string  $value  CIDR notation e.g. "192.168.10.16/28"
     * @param  bool  $negate  Whether to negate the expression
     * @return string
     */
    protected function buildPrefixSql(string $field, string $value, bool $negate): string
    {
        $value = trim($value, '"\'');

        if (! str_contains($value, '/')) {
            $value .= filter_var($value, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? '/128' : '/32';
        }

        [$net, $prefix_len] = explode('/', $value, 2);
        $prefix_len = (int) $prefix_len;

        // Quote field correctly as `table`.`column` or just `column`
        $parts = explode('.', $field, 2);
        $quoted_field = count($parts) === 2
            ? "`{$parts[0]}`.`{$parts[1]}`"
            : "`$field`";

        // Detect if field stores a network/prefix string (e.g. "x.x.x.x/yy")
        // vs a plain address (devices.ip, ipv6_addresses.ipv6_compressed etc.)
        $network_fields = ['ipv4_network', 'ipv6_network'];
        $is_network_field = isset($parts[1]) && in_array($parts[1], $network_fields);

        // devices.ip is stored as varbinary(16) via inet_pton(); all other IP columns are text
        $is_binary_field = ($parts[0] ?? '') === 'devices' && ($parts[1] ?? '') === 'ip';

        if (filter_var($net, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
            // Clamp to [0,32] — a negative shift or >32 bit-shift throws ArithmeticError on PHP 8
            $prefix_len = max(0, min(32, $prefix_len));
            $mask = $prefix_len > 0 ? ((~0 << (32 - $prefix_len)) & 0xFFFFFFFF) : 0;
            $network = ip2long($net) & $mask;

            if ($is_binary_field) {
                $positive_sql = "(LENGTH($quoted_field) = 4 AND (CONV(HEX($quoted_field), 16, 10) & $mask) = $network)";
            } else {
                $ip_expr = $is_network_field
                    ? "INET_ATON(SUBSTRING_INDEX($quoted_field, '/', 1))"
                    : "INET_ATON($quoted_field)";
                $positive_sql = "($ip_expr & $mask) = $network";
            }
        } elseif (filter_var($net, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
            // Clamp to [0,128] — a boundary byte beyond 16 produces ORD('')=0, silently matching everything
            $prefix_len = max(0, min(128, $prefix_len));
            $positive_sql = $is_binary_field
                ? $this->buildIPv6BinaryPrefixSql($quoted_field, $net, $prefix_len)
                : $this->buildIPv6PrefixSql($quoted_field, $net, $prefix_len, $is_network_field, false);
        } else {
            // Not a valid IPv4 or IPv6 address — return a safe no-match rather than interpolating
            // arbitrary user input into SQL (SQL injection guard).
            return $negate ? '(1=1)' : '(1=0)';
        }

        if (! $negate) {
            return $positive_sql;
        }

        // For joined tables use NOT EXISTS so "not_in_prefix" means "device has no address in prefix",
        // not "device has at least one address outside prefix" (which the plain NOT gives with a LEFT JOIN).
        $table = $parts[0];
        if ($table !== 'devices') {
            $path = $this->schema->findRelationshipPath($table, 'devices');
            if ($path && count($path) >= 2) {
                return $this->buildNotExistsSql($path, $positive_sql);
            }
        }

        // Confirmed unreachable for ipv4_networks/ipv6_networks, the only tables
        // not_in_prefix reaches today -- both resolve a real 2+ element path via
        // ports->ipv4_addresses/ipv6_addresses (verified by actually running this
        // parser against real schema data, not just reading the code). If this
        // ever fires for a table added later, that table's relationship path
        // needs registering -- this plain NOT is the wrong semantic for a
        // multi-row join and isn't a safe degradation to fall back on.
        return "NOT ($positive_sql)";
    }

    /**
     * Wrap a positive prefix expression in a correlated NOT EXISTS subquery so that
     * "not_in_prefix" means "the device has no row in the given table matching the prefix".
     *
     * @param  array  $path  Relationship path from 'devices' to the field table,
     *                       e.g. ['devices', 'ports', 'ipv4_addresses']
     * @param  string  $positive_check  The positive prefix SQL expression to negate
     * @return string
     */
    private function buildNotExistsSql(array $path, string $positive_check): string
    {
        // path[0] = 'devices', path[1] = first joined table (anchor), ...
        $anchor_table = $path[1];
        $anchor_glue = $this->getGlue('devices', $anchor_table);
        // anchor_glue is e.g. "devices.device_id = ports.device_id"
        // rewrite as "ports.device_id = devices.device_id" for the subquery WHERE
        $glue_parts = explode(' = ', $anchor_glue, 2);
        if (count($glue_parts) !== 2) {
            // Unexpected glue format — fall back to plain NOT rather than producing broken SQL
            return "NOT ($positive_check)";
        }
        [$devices_col, $anchor_col] = $glue_parts;
        $where_anchor = "$anchor_col = $devices_col";

        $joins = [];
        for ($i = 1; $i < count($path) - 1; $i++) {
            $right = $path[$i + 1];
            $glue = $this->getGlue($path[$i], $right);
            $joins[] = "INNER JOIN `$right` ON $glue";
        }

        $joins_sql = $joins ? ' ' . implode(' ', $joins) : '';

        return "NOT EXISTS (SELECT 1 FROM `$anchor_table`{$joins_sql} WHERE $where_anchor AND $positive_check)";
    }

    /**
     * Build a SQL expression for IPv6 prefix membership testing.
     * Uses SUBSTRING on INET6_ATON binary output for both byte-aligned
     * and non-byte-aligned prefix lengths.
     *
     * @param  string  $quoted_field  Already-quoted SQL field expression
     * @param  string  $net  IPv6 network address e.g. "fd42:cafe:d00d::"
     * @param  int  $prefix_len  Prefix length e.g. 64
     * @param  bool  $is_network_field  Whether field stores "addr/prefix" string
     * @param  bool  $negate  Whether to negate the expression
     * @return string
     */
    protected function buildIPv6PrefixSql(string $quoted_field, string $net, int $prefix_len, bool $is_network_field, bool $negate): string
    {
        $full_bytes = intdiv($prefix_len, 8);
        $remainder_bits = $prefix_len % 8;

        $addr_expr = $is_network_field
            ? "SUBSTRING_INDEX($quoted_field, '/', 1)"
            : $quoted_field;

        $field_aton = "INET6_ATON($addr_expr)";
        $net_aton = "INET6_ATON('$net')";

        if ($full_bytes > 0) {
            $sql = "SUBSTRING($field_aton, 1, $full_bytes) = SUBSTRING($net_aton, 1, $full_bytes)";
        } else {
            // /0 matches everything
            $sql = '1=1';
        }

        if ($remainder_bits > 0) {
            $boundary_byte = $full_bytes + 1;
            $mask = (0xFF << (8 - $remainder_bits)) & 0xFF;
            $sql .= " AND ORD(SUBSTRING($field_aton, $boundary_byte, 1)) & $mask"
                  . " = ORD(SUBSTRING($net_aton, $boundary_byte, 1)) & $mask";
        }

        if ($negate) {
            $sql = "NOT ($sql)";
        }

        return $sql;
    }

    /**
     * Build an IPv6 prefix SQL expression for binary-stored fields (devices.ip, varbinary(16)).
     * Compares raw bytes directly — no INET6_ATON on the field side.
     *
     * @param  string  $quoted_field  Already-quoted SQL field expression
     * @param  string  $net  IPv6 network address e.g. "fd42:cafe:d00d::"
     * @param  int  $prefix_len  Prefix length e.g. 48
     * @return string
     */
    private function buildIPv6BinaryPrefixSql(string $quoted_field, string $net, int $prefix_len): string
    {
        $full_bytes = intdiv($prefix_len, 8);
        $remainder_bits = $prefix_len % 8;
        $net_aton = "INET6_ATON('$net')";

        $conditions = ["LENGTH($quoted_field) = 16"];

        if ($full_bytes > 0) {
            $conditions[] = "SUBSTRING($quoted_field, 1, $full_bytes) = SUBSTRING($net_aton, 1, $full_bytes)";
        }

        if ($remainder_bits > 0) {
            $boundary_byte = $full_bytes + 1;
            $mask = (0xFF << (8 - $remainder_bits)) & 0xFF;
            $conditions[] = "ORD(SUBSTRING($quoted_field, $boundary_byte, 1)) & $mask"
                           . " = ORD(SUBSTRING($net_aton, $boundary_byte, 1)) & $mask";
        }

        return '(' . implode(' AND ', $conditions) . ')';
    }

    /**
     * Expand macro to sql
     *
     * @param  bool  $tables_only  Used when finding tables in query returns an array instead of sql string
     */
    protected function expandMacro(string $subject, bool $tables_only = false, int $depth_limit = 20): array|string
    {
        if (! Str::contains($subject, 'macros.')) {
            return $subject;
        }

        $macros = LibrenmsConfig::get('alert.macros.rule');

        $count = 0;
        while ($count++ < $depth_limit && Str::contains($subject, 'macros.')) {
            $subject = preg_replace_callback('/%?macros.([^ =()]+)/', function ($matches) use ($macros) {
                $name = $matches[1];
                if (isset($macros[$name])) {
                    return $macros[$name];
                } else {
                    return $matches[0]; // this isn't a macro, don't replace
                }
            }, (string) $subject);
        }

        if ($tables_only) {
            preg_match_all('/%([^%.]+)\./', (string) $subject, $matches);

            return array_unique($matches[1]);
        }

        // clean leading %
        $subject = preg_replace('/%([^%.]+)\./', '$1.', (string) $subject);

        // wrap entire macro result in parenthesis if needed
        if (! (Str::startsWith($subject, '(') && Str::endsWith($subject, ')'))) {
            $subject = "($subject)";
        }

        return $subject;
    }

    /**
     * Generate glue and first part of sql query for this rule
     *
     * @param  string  $target  the name of the table to target, for alerting, this should be devices
     * @return string[]
     */
    protected function generateGlue(string $target = 'devices'): array
    {
        $tables = $this->getTables();  // get all tables in query

        // always add the anchor to the target table
        $anchor = $target . '.' . $this->schema->getPrimaryKey($target) . ' = ?';
        $glue = [$anchor];

        foreach ($tables as $table) {
            $path = $this->schema->findRelationshipPath($table, $target);
            if ($path) {
                foreach (array_pairs($path) as $pair) {
                    [$left, $right] = $pair;
                    $glue[] = $this->getGlue($left, $right);
                }
            }
        }

        // remove duplicates
        return array_unique($glue);
    }

    /**
     * Get glue sql between tables. Resolve fields to use.
     */
    public function getGlue(string $parent, string $child): string
    {
        // first check to see if there is a single shared column name ending with _id
        $shared_keys = array_filter(array_intersect(
            $this->schema->getColumns($parent),
            $this->schema->getColumns($child)
        ), fn ($table) => Str::endsWith($table, '_id'));

        if (count($shared_keys) === 1) {
            $shared_key = reset($shared_keys);

            return "$parent.$shared_key = $child.$shared_key";
        }

        $parent_key = $this->schema->getPrimaryKey($parent);
        $flipped = empty($parent_key);
        if ($flipped) {
            // if the "parent" table doesn't have a primary key, flip them
            [$parent, $child] = [$child, $parent];
            $parent_key = $this->schema->getPrimaryKey($parent);
        }
        $child_key = $parent_key;  // assume the column names match

        if (! $this->schema->columnExists($child, $child_key)) {
            // if they don't match, guess the column name from the parent
            if (Str::endsWith($parent, 'xes')) {
                $child_key = substr($parent, 0, -2) . '_id';
            } else {
                $child_key = preg_replace('/s$/', '_id', $parent);
            }

            if (! $this->schema->columnExists($child, $child_key)) {
                $child_key = $this->schema->getPrimaryKey($child);
                \Log::warning("QueryBuilderParser: Warning, guessing glue from $child.$child_key to $parent.$parent_key");
            }
        }

        if ($flipped) {
            return "$child.$child_key = $parent.$parent_key";
        }

        return "$parent.$parent_key = $child.$child_key";
    }

    /**
     * Get an array of this rule ready for jQuery QueryBuilder
     *
     * @return array
     */
    public function toArray(): array
    {
        return $this->builder;
    }

    /**
     * Specify data which should be serialized to JSON
     *
     * @link https://php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed data which can be serialized by <b>json_encode</b>,
     *               which is a value of any type other than a resource.
     *
     * @since 5.4.0
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return $this->builder;
    }
}
