<?php
$oidBase = '.1.3.6.1.4.1.24693.1.1.';
$voltageOids = array();
$sysOid = explode(".", $device["sysObjectID"]);
$modelNumber = $sysOid[count($sysOid)-1];

if(substr($device["sysDescr"], 0, 6) == "FB2900"){
    // It's a 2900
    $monitoringMib = "FB2900-MONITORING";
    $voltageOids = array(
        "1" => array("description" => "1.1V Reference Voltage",
                     "crit_low" => 1.0,
                     "warn_low" => 1.05,
                     "warn_high" => 1.15,
                     "crit_high" => 1.2),
        "2" => array("description" => "1.325V Reference Voltage",
                     "crit_low" => 1.315,
                     "warn_low" => 1.32,
                     "warn_high" => 1.33,
                     "crit_high" => 1.335),
        "3" => array("description" => "1.35V Reference Voltage",
                     "crit_low" => 1.25,
                     "warn_low" => 1.30,
                     "warn_high" => 1.40,
                     "crit_high" => 1.45),
        "4" => array("description" => "3.3V Reference Voltage",
                     "crit_low" => 3.2,
                     "warn_low" => 3.25,
                     "warn_high" => 3.35,
                     "crit_high" => 3.4),
        "5" => array("description" => "5.0V Reference Voltage",
                     "crit_low" => 4.9,
                     "warn_low" => 4.95,
                     "warn_high" => 5.05,
                     "crit_high" => 5.10),
        "6" => array("description" => "Power Supply Voltage",
                     "crit_low" => 11.9,
                     "warn_low" => 11.95,
                     "warn_high" => 12.05,
                     "crit_high" => 12.1),
        "7" => array("description" => "True Random Number Generator Voltage",
                     "crit_low" => 1.0,
                     "warn_low" => 1.05,
                     "warn_high" => 12.15,
                     "crit_high" => 12.2),
    );
}elseif((substr($device["sysDescr"], 0, 6) == "FB6000") ||
        (($modelNumber >= 6000) && ($modelNumber <= 7000))){
    // It's a 6000
    $voltageOids = array(
        "1" => array("description" => "PSU A Output Voltage",
                     "crit_low" => 10.0,
                     "warn_low" => 11.4,
                     "warn_high" => 12.6,
                     "crit_high" => 14.0),
        "2" => array("description" => "PSU B Output Voltage",
                     "crit_low" => 10.0,
                     "warn_low" => 11.4,
                     "warn_high" => 12.6,
                     "crit_high" => 14.0),
        "3" => array("description" => "+12V",
                     "crit_low" => 10.0,
                     "warn_low" => 11.4,
                     "warn_high" => 12.6,
                     "crit_high" => 14.0),
        "4" => array("description" => "+3.3V",
                     "crit_low" => 3.2,
                     "warn_low" => 3.25,
                     "warn_high" => 3.35,
                     "crit_high" => 3.4),
        "5" => array("description" => "+1.8V",
                     "crit_low" => 1.7,
                     "warn_low" => 1.75,
                     "warn_high" => 1.85,
                     "crit_high" => 1.90),
        "6" => array("description" => "+1.2V",
                     "crit_low" => 1.1,
                     "warn_low" => 1.15,
                     "warn_high" => 1.25,
                     "crit_high" => 1.3),
        "7" => array("description" => "+1.1V",
                     "crit_low" => 0.9,
                     "warn_low" => 1.0,
                     "warn_high" => 1.2,
                     "crit_high" => 1.3),
        "8" => array("description" => "+3.3V Fan Power",
                     "crit_low" => 3.2,
                     "warn_low" => 3.25,
                     "warn_high" => 3.35,
                     "crit_high" => 3.4),
        "9" => array("description" => "+1.2V Fan Power",
                     "crit_low" => 1.0,
                     "warn_low" => 1.1,
                     "warn_high" => 1.3,
                     "crit_high" => 1.4),
    );
}

foreach($voltageOids as $oid => $cfg){
    discover_sensor(
        $valid['sensor'],
        'voltage',
        $device,
        $oidBase . $oid,
        $oid,
        'firebrick',
        $cfg["description"],
        (isset($cfg["divisor"]) ? $cfg["divisor"] : '1000'),
        '1',
        (isset($cfg["crit_low"]) ? $cfg["crit_low"] : 0),
        (isset($cfg["warn_low"]) ? $cfg["warn_low"] : 0),
        (isset($cfg["warn_high"]) ? $cfg["warn_high"] : 15),
        (isset($cfg["crit_high"]) ? $cfg["crit_high"] : 20),
        );
}
