all:
  children:
    alphabridge_devices:
      hosts:
        bridge1:
          ansible_host: "192.168.200.242"  # Device IP
          ansible_user: "admin"  # Telnet username
          ansible_password: "admin"  # Telnet password
          ansible_connection: local
          become: true
