name: Report an issue with LibreNMS
description: Bugs/issues only, no requests!
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting generic bugs/issues only!
  
        * [Report a device issue here](https://github.com/librenms/librenms/issues/new?template=device_bug.yml)
        * [Add Device request here](https://community.librenms.org/c/device-requests/12)
        * [I have a question or need support](https://www.librenms.org/#support)
        
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers.
        Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    validations:
      required: true  
    attributes:
      label: Output of ./validate.php
      description: |
        Please post the output of running: /opt/librenms/validate.php
      render: txt
  - type: input
    attributes:
      label: What was the last working version of LibreNMS?
      placeholder: 21.7.0
      description: If known, otherwise leave blank.
 
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: |
        For example, error messages, or stack traces.
        *Hint: /opt/librenms/logs/*
      render: txt
