# PHP-SNMP needs the following to set -OUt by default
numericTimeticks 1
dontPrintUnits 1
# -OX - may fix our SNMP walk issues, but it breaks the legacy snmp_get_multi() function
#extendedIndex 1
# Equivalent of -Pu (allows underscores in MIBS because we have MIBs that need this, and also avoids a memory leak in the library)
mibAllowUnderline 1
