<?php

/*
 | !!!! DO NOT EDIT THIS FILE !!!!
 |
 | You can change settings by setting them in the environment or .env
 | If there is something you need to change, but is not available as an environment setting,
 | request an environment variable to be created upstream or send a pull request.
 */

return [

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'legacy',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],

        'token' => [
            'driver' => 'token_driver',
            'provider' => 'token_provider',
            'hash' => false,
        ],
    ],

    'providers' => [
        'legacy' => [
            'driver' => 'legacy',
            'model' => App\Models\User::class,
        ],
    ],

];
