name: Notify Discord on PR Merge with Specific Tag

on:
  pull_request:
    types:
      - closed

jobs:
  notify-discord:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification to Discord
        if: contains(github.event.pull_request.labels.*.name, 'Breaking-Change')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_ANNOUNCEMENT }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_MESSAGE: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          PAYLOAD=$(jq -n \
            --arg title "$PR_TITLE" \
            --arg url "$PR_URL" \
            --arg body "$PR_MESSAGE" \
            '{content: ":rotating_light: A breaking change pull request has been merged! :rotating_light:\n\n**Title**: \($title)\n[View PR](\($url))\n\n\($body)"}')
      
          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "$DISCORD_WEBHOOK_URL"
