<?php

namespace App\Plugins\ExamplePlugin;

use App\Plugins\Hooks\MenuEntryHook;

class Menu extends MenuEntryHook
{
    public function data(): array
    {
        count(null);
        return parent::data(); // TODO: Change the autogenerated stub
    }
}
